// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjffltybucegxnjvwema.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZmZsdHlidWNlZ3huanZ3ZW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDA1ODQsImV4cCI6MjA3MjgxNjU4NH0.djrKxNLme3KCLigoX7DpNwV2yQvr7V5OdMD2ZMTLi6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window === "undefined" ? undefined : window.sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
